### ISSUE TITLE
Using the nginx-pagespeed image with jwilder/nginx-proxy

### ISSUE THREAD

**Issue by snoby** [27Bslash6/docker#11]
Hi,
Great images that i've created.  I currently use[ jwilder's nginx-proxy](https://github.com/jwilder/nginx-proxy) to front all my web services.  This also has the addon to automatically handle TLS termination and [letsencrypt certificate maintenance](https://github.com/jwilder/nginx-proxy#ssl-support-using-letsencrypt).  

I was wondering how you would recommend disabling the SSL in the nginx config ( perhaps as a pull request).  I tried exporting `SSL_ENABLED=false` because of this [line in /etc/service/nginx/run](https://github.com/27Bslash6/docker/blob/5917031ee0e93225af114d9ae185004ff47c98b7/nginx-pagespeed/etc/service/nginx/run#L16)
It seems to have worked, but wanted to know if you had any more recommendations?
thanks!

**Comment by 27Bslash6** [comment]
Generally `SSL_ENABLED=false` is adequate to disable self-signed certificate generation. 
Along with the required VIRTUAL_HOST and VIRTUAL_PROTO settings from jwilder that ought to be all you need.
