### ISSUE TITLE
Add Lua / Perl Module

### ISSUE THREAD

**Issue by devotox** [27Bslash6/docker#17]
This is needed to be able to script things like making all URLs lowercase

**Comment by 27Bslash6** [comment]
Maybe consider a move away from nginx and use the openresty bundle instead? Brings a lot to the table, notably redis fastcgi caching and LUA, and converting the install is fairly painless: https://github.com/greenpeace/planet4-docker/blob/master/src/planet-4-151612/openresty/bin/install_openresty.sh
