### ISSUE TITLE
NEWRELIC_ENABLED: unbound variable

### ISSUE THREAD

**Issue by stanislavprokopov** [27Bslash6/docker#4]
Tried to run the `funkygibbon/magento2` image and got stuck with this error repeating in the console over and over:

> * php:    pool name   f___ad______
>  * php:    user:  app
>  * php:    group: app
>  * php:    memory_limit:         128M
>  * php:    upload_max_filesize:  30M
>  * php:    post_max_size:        30M
>  * php:    max_execution_time:   300
>  * php:    max_input_vars:       2000
>  * php:    pm.max_children:      6
>  * php:    pm.start_servers:     3
>  * php:    pm.min_spare_servers: 2
>  * php:    pm.max_spare_servers: 3
>  * php:    pm.max_requests:      500
>  * php:    newrelic.enabled:     false
> ./run: line 81: NEWRELIC_ENABLED: unbound variable

Fixed, by adding `NEWRELIC_ENABLED=false` at line 69 in `nginx-php-exim/etc/service/php/run`

**Comment by virtuman** [comment]
had the same error, needed to specify false if you don't want to use newrelic

**Comment by 27Bslash6** [comment]
Thanks for this, fixed in https://github.com/27Bslash6/docker/commit/4cc7cbc8bb8ebef1b4fed4be56e3a28ef1479ae3
